server:
  port: ${SERVER_PORT:6070}
  servlet:
    context-path: /notification-service

spring:
  application:
    name: notification-service

  # Thêm cấu hình Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  security:
    oauth2:
      resourceserver:
        jwt:
          # Đã sửa lại thành iluttmab
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8888/realms/iluttmab}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:6059/eureka}
  instance:
    prefer-ip-address: true

grpc:
  server:
    port: ${NOTIFICATION_SERVICE_GRPC_PORT:6170}