server:
  port: 6070

spring:
  application:
    name: notification-service
jwt:
  secret: ${JWT_SECRET:default-secret-key-for-development-only-must-be-long-enough-256-bits}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:6059/eureka}

grpc:
  server:
    port: ${NOTIFICATION_SERVICE_GRPC_PORT:6169}
