spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/identityservice
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  servlet:
    context-path: /identity-service
  port: 8082

app:
  prefix: ${API_PREFIX:/api/v1}
  security:
    cookie:
      secure: ${COOKIE_SECURE:false}
      same-site: ${COOKIE_SAME_SITE:Strict}
    keycloak:
      server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8888}
      realm: ${KEYCLOAK_REALM:unicall}
      client-id: ${KEYCLOAK_CLIENT_ID:unicall-client}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:BnaPyiYRiG0LP8sGdQNuCp1eZ32IFIya}
      admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:unicall-admin-client}
      admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:qEtqS9STfjKuzU99109MTtlZfCcL8UBi}

grpc:
  client:
    user-service:
      address: ${USER_SERVICE_GRPC_ADDRESS:static://localhost:9091}
      negotiationType: plaintext
  user-service:
    deadline-ms: ${USER_SERVICE_GRPC_DEADLINE_MS:5000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:6061/eureka/}
  instance:
    prefer-ip-address: true