server:
  port: 6065

spring:
  application:
    name: SHIPPING-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/shipping
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:6061/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

