server:
  port: 6071

spring:
  application:
    name: SHIPPING-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/shipping
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:6059/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

grpc:
  server:
    port: ${SHIPPING_SERVICE_GRPC_PORT:6171}

user-service:
  base-url: ${USER_SERVICE_BASE_URL:http://localhost:6073}
