server:
  port: ${ORDER_SERVICE_PORT:6065}
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${ORDER_MONGO_URI:mongodb://root:123456@localhost:6000/order-service?authSource=admin}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6002}
      connect-timeout: 2s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: ${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}

app:
  security:
    permit-all-endpoints:
      - /v3/api-docs/**
      - /swagger-ui/**
      - /actuator/health
    allowed-origins:
      - ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001,http://localhost:3003,http://localhost:3004}

grpc:
  server:
    port: ${ORDER_SERVICE_GRPC_PORT:6165}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:6059/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:WARN}
    com.tam: ${LOGGING_LEVEL_COM_TAM:INFO}
  pattern:
    console: "%d{ISO8601} [%X{traceId:-},%X{spanId:-}] [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{ISO8601} [%X{traceId:-},%X{spanId:-}] [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/order-service.log
    max-size: 10MB
    max-history: 7
management:
  endpoints:
    web:
      exposure:
        include: beans