syntax = "proto3";

package pc_store.user.v1;

option java_multiple_files = true;
option java_package = "iuh.fit.pc_store.grpc.user.v1";
option java_outer_classname = "UserServiceProto";

service UserService {
  rpc CreateUserProfile(CreateUserProfileRequest) returns (CreateUserProfileResponse);
  rpc DeleteUserProfile(DeleteUserProfileRequest) returns (DeleteUserProfileResponse);
  rpc GetUserProfileByIdentity(GetUserProfileByIdentityRequest) returns (GetUserProfileByIdentityResponse);
  rpc UpdateUserProfile(UpdateUserProfileRequest) returns (UpdateUserProfileResponse);
}

message Address {
  string id = 1;
  string country = 2;
  string province = 3;
  string city = 4;
  string ward = 5;
  string street = 6;
  bool isDefault = 7;
  repeated string phoneContacts = 8;
  bool isActive = 9;
}

message CreateUserProfileRequest {
  string identityUserId = 1;
  string defaultPhoneNumber = 2;
  string defaultEmail = 3;
  string firstName = 4;
  string lastName = 5;
  string gender = 6;
  string dateOfBirth = 7;
  string avatar = 8;
}

message CreateUserProfileResponse {
  string id = 1;
  string identityUserId = 2;
}

message DeleteUserProfileRequest {
  string identityUserId = 1;
}

message DeleteUserProfileResponse {
  bool deleted = 1;
}

message GetUserProfileByIdentityRequest {
  string identityUserId = 1;
}

message GetUserProfileByIdentityResponse {
  string id = 1;
  string identityUserId = 2;
  string defaultPhoneNumber = 3;
  string defaultEmail = 4;
  string firstName = 5;
  string lastName = 6;
  string gender = 7;
  string dateOfBirth = 8;
  string avatar = 9;
  bool isActive = 10;
  repeated Address addresses = 11;
}

message UpdateUserProfileRequest {
  string identityUserId = 1;
  string defaultPhoneNumber = 2;
  string defaultEmail = 3;
  string firstName = 4;
  string lastName = 5;
  string gender = 6;
  string dateOfBirth = 7;
  string avatar = 8;
}

message UpdateUserProfileResponse {
  string id = 1;
  bool updated = 2;
}
