server:
  port: 6068

spring:
  application:
    name: promotion-service

  datasource:
    url: jdbc:postgresql://localhost:5432/promotion
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false

jwt:
  secret: ${JWT_SECRET:default-secret-key-for-development-only}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:6059/eureka}

grpc:
  server:
    port: ${PROMOTION_SERVICE_GRPC_PORT:6168}
