server:
  port: ${SERVER_PORT:6066}
  servlet:
    context-path: /payment-service

spring:
  main:
    # Cho phép ghi đè Bean nếu bị trùng tên
    allow-bean-definition-overriding: true
  application:
    name: payment-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/iluttmab}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/payment
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/iluttmab}
    permit-all-endpoints:
      - /v3/api-docs/**
      - /swagger-ui/**
      - /actuator/health
    allowed-origins:
      - ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:6059/eureka}
  instance:
    prefer-ip-address: true

grpc:
  server:
    port: ${PAYMENT_SERVICE_GRPC_PORT:6166}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG