server:
  port: ${IDENTITY_SERVICE_PORT:6062}
  servlet:
    context-path: /identity-service

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: identity-service
  jmx:
    enabled: false
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://${IDENTITY_DB_HOST:localhost}:${IDENTITY_DB_PORT:6001}/${IDENTITY_DB_NAME:identityservice}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: ${IDENTITY_DB_USER:root}
    password: ${IDENTITY_DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 36000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:6059/eureka/}
  instance:
    prefer-ip-address: true

grpc:
  client:
    user-service:
      address: static://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_GRPC_PORT:6163}
      negotiation-type: plaintext

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:WARN}
    com.devteria: ${LOGGING_LEVEL_COM_TAM:INFO}
  pattern:
    console: "%d{ISO8601} [%X{traceId:-},%X{spanId:-}] [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{ISO8601} [%X{traceId:-},%X{spanId:-}] [%thread] %-5level %logger{36} - %msg%n"
