server:
  port: ${SERVER_PORT:6072}
  servlet:
    context-path: /search-service # Thêm vào để ko bị 404

spring:
  application:
    name: search-service

  # Cấu hình Elasticsearch
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    # Nếu ES của mày cài password thì dùng 2 dòng dưới, ko thì bỏ qua
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:changeme}

  # Bổ sung bảo mật (Bắt buộc phải có để Gateway forward token xuống)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8888/realms/iluttmab}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:6059/eureka}
  instance:
    prefer-ip-address: true

grpc:
  server:
    port: ${SEARCH_SERVICE_GRPC_PORT:6172}