server:
  port: 6070

spring:
  application:
    name: search-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:6059/eureka}

grpc:
  server:
    port: ${SEARCH_SERVICE_GRPC_PORT:6170}
