apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: chat-service
          image: registry.gitlab.com/tam1ttam-group/pc_store_microservice/chat-service:latest
          ports:
            - containerPort: 8085
            - containerPort: 8099
          env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx256m"
          envFrom:
            - secretRef:
                name: app-secrets
            - configMapRef:
                name: app-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 90
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: app
spec:
  selector:
    app: chat-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
    - name: socketio
      port: 8099
      targetPort: 8099
