server {
    listen 80;
    server_name taam.io.vn; # Ở máy mày thì sửa thành tam.local nếu thích

    resolver 127.0.0.11; # Docker DNS thần thánh

    # 1. Storefront (Root)
    location / {
        proxy_pass http://storefront:3000;
        proxy_set_header Host $host;
    }

    # 2. Backoffice
    location /admin/ {
        proxy_pass http://backoffice:3001/; # Dấu / cuối để cắt chữ /admin/
        proxy_set_header Host $host;
    }

    # 3. Gateway API
    location /api/ {
        proxy_pass http://gateway:6060/; # Cắt chữ /api/ trước khi đẩy vào Gateway
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 4. Keycloak Auth
    location /auth/ {
        proxy_pass http://identity:8181/; 
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}